version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email | docker login --username AWS --password-stdin 313401839503.dkr.ecr.us-east-1.amazonaws.com)
      - REPOSITORY_URI=313401839503.dkr.ecr.us-east-1.amazonaws.com/test-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
 
